### ISSUE TITLE
Can I build VST3 consolidated plugin on Debian 11?

### ISSUE THREAD

**Issue by triss** [baconpaul/airwin2rack#110]
Hi, Are there build instructions for the consolidated plugin for older Linux platforms?

I'd like to build this for a Debian 11 environment.

**Comment by triss** [comment]
Ah, wonderful. I'm being dense though! Where do I find the build instructions?

(thanks for your work by the way... I've fallen in love with most of the airwindows plugins I've understood and you've just made doing so a hell of a lot easier!)

**Comment by baconpaul** [comment]
The readme has them 

https://github.com/baconpaul/airwin2rack?tab=readme-ov-file#the-juce-plugin
