### ISSUE TITLE
Consolidated plugin issue, VST3, Ableton, Windows. Improper recall of parameters.

### ISSUE THREAD

**Issue by JoeSayerUK** [baconpaul/airwin2rack#112]
Sorry if this is the wrong place to post this. 

Having an issue with the consolidated plugin where the plugin fails to recall in the correct program / mode. Or the plugin will recall the proper settings, but the exposed parameters will be labelled incorrectly, using parameter names from the init 'Galactic' program.

Reproducing this issue on Ableton 11.3.21, when recalling saved 'ADG' device group presets with parameters assigned to macros. If custom labels to the macros are not provided, the macros and exposed parameters will recall with incorrect names. The same behaviour applies to loading projects containing instances of the plugin.

This issue creates confusion when recalling projects in which the parameters are being automated, because the automated parameters will be labelled incorrectly.

![AW consolidated recall issue](https://github.com/baconpaul/airwin2rack/assets/22054530/159d1d8b-368a-4aaa-923e-ba7ccf24d82e)

Left: Device group recalled **with** custom macro labels provided. The correct program mode has loaded but the exposed parameters are incorrectly named.

Right: Device group recalled **without** custom macro labels. Similar to above, but now the macros have taken on the incorrect parameter names as reported by the plugin.

**Comment by baconpaul** [comment]
Ahh so the recall and sound is correct but the live ui has not updated the macro knobs names?

**Comment by baconpaul** [comment]
Question - it will destroy your settings but if you jog the type up and down do the names show correctly?

**Comment by JoeSayerUK** [comment]
> Ahh so the recall and sound is correct but the live ui has not updated the macro knobs names?

This is correct. In all cases when recalling the plugin, either by duplication or loading a project or device group, the exposed parameters will take on the names associated with the init 'Galactic' program mode. 

Just in case you aren't familiar with Ableton Live specifically, by 'exposed parameters' I'm referring to the parameters visible when clicking the 'Unfold Device Parameters' toggle in the UI. These are distinct from the macros on the left, which are manually assigned to the exposed parameters.

Unless the user specifies a custom name to the macros, the macros will be labelled automatically according to the parameters they are assigned to.

It seems to the case that the automatically designated macro labels are not saved with the device group file, but are dynamically assigned when the group is loaded. So when the plugin loads with incorrect parameter names, the macro labels are updated to reflect the incorrect parameter names.

By manually providing names to the macros before saving the device group, the automatic label assignment is prevented, so the macros now recall with the correct names, but the exposed parameters still have incorrect names.

I hope that makes sense!

> Question - it will destroy your settings but if you jog the type up and down do the names show correctly?

If I manually toggle the program to a different one then back to the correct one, the exposed parameters do update to the correct names.

But, the macros labels do not update. It seems the automatic macro label assignment only occurs when the group is loaded.

I'm not familiar with plugin development, but my suspicion is that the plugin always initializes to 'Galactic' before proceding to recall the intended program mode, causing the the exposed parameters to populate with the names associated with 'Galactic'. Could this be the case?

**Comment by baconpaul** [comment]
Yes that’s exactly what it does but I do call the vst3 api to invalidate parameter names when I load a new setting so live should get told - but live vst3 sometimes does things in fun and exciting different orders than other hosts so I’ll need to test 

just to be sure you are running the latest version right? There’s a version in the about 

I have live on my Mac. I will try to give this a whirl tomorrow and see what’s happening 

appreciate the detailed explanations. Useful

**Comment by JoeSayerUK** [comment]
Yes, since posting the issue I have tested the latest build, and the problem still occurs.

Thanks for the quick response by the way. I'm a huge fan of the Surge VCV modules and plugin, keep up the excellent work!

**Comment by JoeSayerUK** [comment]
Not a major issue so no rush on this, but would be nice to have a fix eventually.

Definitely possible this is an issue with Live.

Funnily enough, I have seen similar issues to this in VCV Rack / Cardinal.

Interesting because these are the only plugins I can think of which have variable parameter names. Most plugins come with a set of fixed parameters which never change, but AWCons and VCV Rack are a notable exception to this. So this may well be an issue with Ableton handling dynamic / variable parameter names.

I have certainly considered Bitwig, but using Live professionally for 12+ years, I am very heavily invested in Live's tools, Max for Live, file formats etc.

**Comment by baconpaul** [comment]
I was joking about switching daws obviously

surge also changes parameter names in some cases like fx switches. I’ll try that and see what happens too.

**Comment by baconpaul** [comment]
OK this one really bugged me and talking to some other audio devs, I'm not doing anything wrong, so I poked at it some.

Short story: it is definitely a live 11 bug, but there's a workaround (albeit a somewhat silly one) which fixes the problem. I just pushed that and the build finished, so in theory if you grab latest it should all work fine when duplicating and restoring state.

There's a small chance you may see a flicker on the very last param with a name like `live_fix_4241432` for 1ms. If you see that and wonder "what the heck", there's a longer story :)

**Comment by JoeSayerUK** [comment]
Confrming this has now been fixed. Thanks, Paul!

**Comment by baconpaul** [comment]
Wonderful
