### ISSUE TITLE
Add post gain knob to standalone plugin

### ISSUE THREAD

**Issue by jamesWalker55** [baconpaul/airwin2rack#116]
Most of Airwindows' plugins lack a post gain knob to control the output volume. One example out of many:

![image](https://github.com/baconpaul/airwin2rack/assets/30405220/d43b142f-8f4c-4a9c-8ced-e30874ac262b)

This makes it difficult to compare the Wet/Dry signals by toggling the plugin on/off. E.g. This clip plugin will always clip at 0.0dB and I must adjust the pre-FX gain - when I turn off the plugin, the dry signal has a completely different volume level and it is difficult to compare the wet/dry signals by ear.

Adding a simple **post** gain knob would make it significantly easier to A/B the plugin by ear.

**Comment by baconpaul** [comment]
I agree! But this is a dup of #85 where we are consolidating input and output gain controls in the effect. I'll do another feature sweep early this summer and pick that (and some of the others) up. I'm going to close this as dup but it's linked to 85 now. 

Thanks and hope you enjoy the plugin!
