### ISSUE TITLE
airwindows for vcv multi fx?

### ISSUE THREAD

**Issue by XtremeSounds** [baconpaul/airwin2rack#119]
any way we can get a version where we can enable up to 4 effects at once? That would be a really good module I think

**Comment by baconpaul** [comment]
Duplicate the module 4 times is the obvious answer. In a modular environment why wouldn’t you just do that?

**Comment by XtremeSounds** [comment]
Trying to make a small system. I know its software, its an aesthetics things.  There doesn’t seem to be really any multi function / multi fx modules in vcv rack as we see in hardware.

**Comment by baconpaul** [comment]
Right.

So to be honest, I'm not going to write software so you can meet that goal! Basically "compress panel and linear route so you can have a big system that looks like a small system" is a "wont do".

If you want to write such a module though the system here makes all the effects available as a library. But I'm going to close this one.

Thanks

**Comment by airwindows** [comment]
I'm going to confirm that this isn't the intention with Consolidated :) I wrote the individual plugins (and continue to do so) but I'm not the one who'd be able to even do this request, but I will politely request to please not do it. I would like Consolidated not to be a multi-FX, just a host for any one of the plugins that work with it :)

**Comment by XtremeSounds** [comment]
ok leave it alone folks
