### ISSUE TITLE
not all airwindows effects in vcv rack are working 

### ISSUE THREAD

**Issue by XtremeSounds** [baconpaul/airwin2rack#120]
no sound is coming out. starchild 2 galactic2 for example

**Comment by baconpaul** [comment]
The galactic2 default patch requires a big input signal. Either increase the drive or amplify the input

Starchild2 works fine with the below patch

![Screenshot 2024-06-05 at 8 26 06 AM](https://github.com/baconpaul/airwin2rack/assets/13387561/7118728c-a2c7-45d4-a6f1-293df7be235f)

If you want to provide a more fulsome bug report with an included patch and routing that doesn't work, or provide information like your OS and so on, after trying the above, please feel free to reopen.

**Comment by XtremeSounds** [comment]
Ok thanks
