### ISSUE TITLE
add the date the plugin was released

### ISSUE THREAD

**Issue by RustoMCSpit** [baconpaul/airwin2rack#122]
on the website, each plugins release date is displayed.
doing the same on the gui would be cool

**Comment by baconpaul** [comment]
Basically a dup of #101

**Comment by RustoMCSpit** [comment]
sorry changing title

**Comment by RustoMCSpit** [comment]
i meant most recent commit

**Comment by RustoMCSpit** [comment]
know what, i'll add it to yours
