### ISSUE TITLE
Classification problem in "All Plugins"

### ISSUE THREAD

**Issue by fotisandstuff** [baconpaul/airwin2rack#131]
Hello! When I choose "All Plugins", YNotNotch is in the Unclassified category, while it should be in the XYZ Filters.

![image](https://github.com/baconpaul/airwin2rack/assets/44263494/8c1f6b4a-2b73-4d24-8cde-b9c2ea5641bf)

**Comment by baconpaul** [comment]
Thanks!

@airwindows can you update the 'pedia on your next push?

**Comment by airwindows** [comment]
Will do :) *typetypetype* have done. Might not have a plugin for this collection next week, so I have pushed the change without adding another plugin.
