### ISSUE TITLE
CLAP Version loses GUI

### ISSUE THREAD

**Issue by hockinsk** [baconpaul/airwin2rack#139]
Not sure if this is directly a CLAP issue or a Consolidated issue, but after a while of use in Bitwig 5, the CLAP version of Consolidated doesn't seem possible to open anymore, it loses the icon to launch the GUI. I will do some more testing and reply here if I find anything.
![image](https://github.com/baconpaul/airwin2rack/assets/1609513/fd477ef8-382f-454c-b9aa-6cbee0343c96)

**Comment by baconpaul** [comment]
Hmm are you sure those first two devices are Consolidated, and not the (far older) gui free clap? The consolidated shows "Airwindows Consolidated" as the device name, not "Debess" or "ADClip7"

About 2 years ago when clap launched I did an earlier version of air win to clap which made 350 clap plugins in one single clap. Could you have installed that and be running it perhaps?

**Comment by hockinsk** [comment]
I think you're right, I can't re-create it now I'm trying to so I think ignore this and close the thread, no enough coffee for me clearly haha!

**Comment by baconpaul** [comment]
You can delete the old one if you want, which is probably called `airwin-to-clap.clap` and then rescan in bitwig (or it will rescan automatically when you delete it) and then no more confusion.
