### ISSUE TITLE
get rid of extra pointless 0s

### ISSUE THREAD

**Issue by RustoMCSpit** [baconpaul/airwin2rack#145]
![image](https://github.com/user-attachments/assets/f6785097-4f31-435d-bcdb-2c594183480f)

**Comment by RustoMCSpit** [comment]
also it would be cool if instead of just a number, the background also changed to a different color left to right depending on the value.

**Comment by baconpaul** [comment]
Fixed width fixed font is on purpose in the formatters, so gonna leave this one as is thanks,

**Comment by RustoMCSpit** [comment]
> Fixed width fixed font is on purpose in the formatters, so gonna leave this one as is thanks,

no i mean, it's the extra 0s. 0.45**00**

**Comment by RustoMCSpit** [comment]
there are only two needed decimal places after the .

**Comment by baconpaul** [comment]
yeah i know what you meant. it's on purpose.
