### ISSUE TITLE
add tone source collections

### ISSUE THREAD

**Issue by RustoMCSpit** [baconpaul/airwin2rack#146]
a tone source collection

**Comment by RustoMCSpit** [comment]
tone source as in, it makes sound itself

**Comment by baconpaul** [comment]
We have all the airwindows in the plugin so the tone sources which are there are in the plugin now

**Comment by RustoMCSpit** [comment]
> We have all the airwindows in the plugin so the tone sources which are there are in the plugin now

no i mean, make it its own collection

**Comment by baconpaul** [comment]
then i don't understand what you mean.

**Comment by RustoMCSpit** [comment]
anything that makes its own sound should be in a new collection

**Comment by baconpaul** [comment]
Oh I see. That’s up to Chris. We just read his categories here.
