### ISSUE TITLE
No presets in LV2 manifest.ttl after building

### ISSUE THREAD

**Issue by anupam-git** [baconpaul/airwin2rack#149]
Hi,

I built airwin2rack lv2 plugin locally on my Rpi5 and noticed that `manifest.ttl` file do not have any presets available.
Build command : `mkdir build && cd build && cmake .. -DBUILD_JUCE_PLUGIN=TRUE -DCMAKE_BUILD_TYPE=Release && make -j$(nproc) awcons-products`

Tried building both `main` and `v2.12.0` tag and got same result on both. I was hoping to get all the different plugins as preset.

The generated `manifest.ttl` file is as follows :
```
@prefix lv2:   <http://lv2plug.in/ns/lv2core#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix pset:  <http://lv2plug.in/ns/ext/presets#> .
@prefix state: <http://lv2plug.in/ns/ext/state#> .
@prefix ui:    <http://lv2plug.in/ns/extensions/ui#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .

<https://airwindows.com//plugins/Airwindows_Consolidated>
	a lv2:Plugin ;
	lv2:binary <libAirwindows%20Consolidated.so> ;
	rdfs:seeAlso <dsp.ttl> .

<https://airwindows.com//plugins/Airwindows_Consolidated:UI>
	a ui:X11UI ;
	lv2:binary <libAirwindows%20Consolidated.so> ;
	rdfs:seeAlso <ui.ttl> .

<https://airwindows.com//plugins/Airwindows_Consolidated:preset1>
	a pset:Preset ;
	lv2:appliesTo <https://airwindows.com//plugins/Airwindows_Consolidated> ;
	rdfs:label "Airwindows Consolidated" ;
	state:state [ <https://airwindows.com//plugins/Airwindows_Consolidated:Program> "0"^^xsd:int ; ] .
```

**Comment by baconpaul** [comment]
Program change support works horribly across daws so we disabled it 

the code is there, if you look in the processor cpp and turn on use juce programs you will get them

**Comment by anupam-git** [comment]
Hi, I tried adding the `USE_JUCE_PROGRAMS=1` to compile definitions and still manifest.ttl is the same as above. 
Upon closer inspection, found `AWConsolidatedAudioProcessor::getCurrentProgram()` and `AWConsolidatedAudioProcessor::getProgramName` to be returning early with `0` and `Airwindows Consolidated` respectively at all times irrespective of `USE_JUCE_PROGRAMS`.

Would you like a PR with the fix?

**Comment by baconpaul** [comment]
A PR with a fix, as long as it remains off by default, would be wonderful. Perhaps add it as a CMake option?

When I had this turned on it cause da variety of problems in various VST3 daws.

Thank you very much!

**Comment by anupam-git** [comment]
Here is the PR : https://github.com/baconpaul/airwin2rack/pull/151
Added the cmake option to turn on juce programs which defaults to OFF

**Comment by baconpaul** [comment]
Merged thanks

**Comment by anupam-git** [comment]
Great 😁
