### ISSUE TITLE
Up/down arrows in Chris mode

### ISSUE THREAD

**Issue by Vospi** [baconpaul/airwin2rack#152]
Hey there!
Not really a big issue, but:
- if you switch to Chris Order Menus, up/down arrows still seem to work through an alphabetical one, so you can't explore the Chris sorting with the arrows on the interface, only going through the menu.

Windows, ver Aug 24 2024.

Thanks for the wonderful work! Amazing way to really dig into Airwindows.

**Comment by baconpaul** [comment]
Oh yeah wow i can see why that would be.

Let me add it to my 'todo' list for the next couple of weeks. Thanks!

**Comment by baconpaul** [comment]
Hey! I got a bit of time and put this in. Next build in an hour or so should have it

**Comment by Vospi** [comment]
Love this! Thank you!

**Comment by Vospi** [comment]
Hey! I've just updated to 8989ff1, CLAP on Windows, and the sorting works the same.
To clarify:
1) I am in "Chris (Quality) Order Menus"
2) For example, I select Ambience -> Clear Coat from the top of my text list.
3) Then I press a "down" arrow on the interface and expect to get TapeDelay2, the next in "Chris Order". However, I get Doublelay, the next in alphabetical order.

The dropdown menus themselves are fine and were fine for me before.

(The plugin is still very useful, thought-out and beautiful!)

**Comment by baconpaul** [comment]
Hmm I see the exact opposite. That exact test works for me.

Not to be rude but are you sure you are running the updated version? The settings / about menu will show you the build date and hash.

Also are you on collection "All" (although I tried it in other collections too)

**Comment by Vospi** [comment]
I completely understand! No worries.
The plugin says the name of the build I've posted, I made sure before the last post, should've noted that previously :) Sep 2 2024 8989ff1, the window says.

My sorting settings are:
Filter by collection - All Plugins
Show Documentation
Christ (Quality) Order Menus

Doesn't work.
I've tried it in the Basic collection as well.
Also, I somehow have 4 collections? Latest, Basic, Latest and Recommended. Yes, Latest is there 2 times, not a typo

**Comment by baconpaul** [comment]
Yeah I saw that double latest today
That’s just generated from Chris input so I bet he added a trailing space somewhere and I don’t strip it 

ok let me reopen. I don’t understand why it would work for me and not you but I can look again this week

**Comment by baconpaul** [comment]
oh sheesh i realize that (1) i forgot to look at this and (2) when i realized that now and look that I just hadn't committed the code that makes this fix.

I'm so sorry the fix was just uncommitted on my hard drive for a month neglected and forgotten. Should be in a nightly in an hour or so.
