### ISSUE TITLE
Feature Request: Automatic gain compensation

### ISSUE THREAD

**Issue by DocShadrach** [baconpaul/airwin2rack#154]
There are certain plugins that would greatly benefit from some auto gain function. I sometimes use the Melda MAGC, but it would be nice if the DAWplugin had this function built-in as an option. Thank you for all the great work you do!

**Comment by baconpaul** [comment]
Thanks for the nice words and I’m glad you enjoy the plug-in!

im not even sure how I would do this without really interfering with the signal path, plus it’s kinda tricky dsp anyway. other than the attenuators, I’ve not altered the signal at all.

So I’m going to close this as a “won’t add” - I think the right solution is indeed a tool downstream if you want it
