### ISSUE TITLE
Cannot load CLAP version in Bitwig 5.2.4 [macOS]

### ISSUE THREAD

**Issue by lucaromagnoli** [baconpaul/airwin2rack#161]
Hello,

I'm getting this error when I try to load the CLAP version of the plugin in Bitwig 5.2.4. 
<img width="287" alt="Screenshot 2024-09-30 at 08 15 06" src="https://github.com/user-attachments/assets/54d83016-54f2-425b-8c8d-606509dca24c">

PaulXstretch.clap is correctly installed in my CLAP directory if it helps

macOS Sonoma 14.6.1

**Comment by baconpaul** [comment]
Wow that looks like bitwig is trying to load paulstreatch from airwindows

Can you force a full rescan in bitwig? Seems like they are asking me for the wrong thing.

**Comment by lucaromagnoli** [comment]
There doesn't seem to be an option for a full rescan in Bitwig, it's always running in the background.

I also tried to remove PaulXStretch.clap but I'm still getting the same error.

I will try to open a ticket with Bitwig support.

**Comment by baconpaul** [comment]
I remember in the very early days of clap support there was a way you could get bitwig internal indices confused yeah but I don’t remember the fix - I’ll dig around on my laptop later and see if I can find it but I think you just gave a corrupted plugin index tbh

**Comment by lucaromagnoli** [comment]
Okay, I got a reply from Bitwig support and they suggested to delete files in

`/Users/username/Library/Application Support/Bitwig/Bitwig Studio/index`

That fixed the problem.

Sorry for opening an issue when I should have contacted Bitwig support beforehand.

**Comment by baconpaul** [comment]
No need to apologize! Hope you enjoy the plugin and glad it got resolved!
