### ISSUE TITLE
The plugin no longer works (Reaper on Windows 7)

### ISSUE THREAD

**Issue by DocShadrach** [baconpaul/airwin2rack#170]
It was working fine until version AirwindowsConsolidated-2024-11-11-f9a6f01-Windows-64bit-setup. The AirwindowsConsolidated-2024-11-21-a14983e-Windows-64bit-setup version has already stopped working, both in VST3 and CLAP. Reaper does not load it.

**Comment by baconpaul** [comment]
All yes I'm pretty sure our build pipeline wont build for windows 7 now we moved to JUCE 8, which requires Windows 10.

**Comment by DocShadrach** [comment]
Oh, that's a shame :(

**Comment by baconpaul** [comment]
If you have a compiler installed, you can back down the JUCE change and build yourself. It should work. There's some advantages to JUCE 8 but the JUCE 7 version will still compile.

**Comment by DocShadrach** [comment]
No, I don't have the compiler installed, but that's fine, I'll have to stick with the Consolidated version that works for me and install the new plugins separately. For now I want to stay on Windows 7. Thanks. 

The weird thing is that the vast majority of plugins still work on Windows 7, so I found it a little odd that Consolidated stopped working.

**Comment by baconpaul** [comment]
juce 8 is about 2 months since 8.0 release; as devs upgrade more stuff will stop working. hate to be the bearer of bad news.

I'm going to close this since I don't think there's anything to be done but if you do decide you want to back down and self build, please do let me know and I'm happy to share instructions.

**Comment by baconpaul** [comment]
Hi

So you were not alone in the windows 7 camp and @airwindows bugged me about it a bit, so this evening I set up a parallel juce 7 build in our pipeline. (I also moved our macOS version back to 10.11 but you don't care about that).

If you look https://github.com/baconpaul/airwin2rack/releases/tag/DAWPlugin you will see some installers have the `-windows7` name in them. If you could try one of those and let me know if it works I would greatly appreciate it.

It won't have the laudable features of JUCE 8 (direct2d, hardware graphics, better font rendering, and more) but I left the code bidirectionally compatible with 7 so its just burning some energy at the power plant next to the azure computers to do this. But I have no way to test it. Any feedback would be welcome!

The one without -windows7 in the name is the recommended one for all W10 and W11 users still, of course.

Thanks!

**Comment by DocShadrach** [comment]
Wow. That's awesome 👍

I was quite worried about this 😂

I just tried it and it works fine. Thank you so much for doing this and
thank you so much for letting me know!

🤘

**Comment by baconpaul** [comment]
Super! Closing this again then
