### ISSUE TITLE
UI Doesn't Display

### ISSUE THREAD

**Issue by woodywall** [baconpaul/airwin2rack#175]
I'm not certain this is an Airwindows Consolidated issue but I've looked around and can't find anything else. The latest release that works properly for me is November 3 f8944f7. Any release I have installed since then does not display the UI when opening the plugin--only a blank gray rectangle that would normally contain the UI elements. If I toggle Reaper's native UI button, all the controls are displayed with Reaper's native UI, but without any way to change to another plugin or see the documentation.

OS: Windows 10 Home 22H2
DAW: Reaper 7.28.

**Comment by baconpaul** [comment]
I know it sounds odd, but a day or two ago I added a new build which shows up with the `-windows7` tag

I wonder if downloading that would fix it for you?

I upgraded to juce 8 which places a higher requirement on directtx and so on (with a wide number of benefits) but we are still providing a build on the old tech.

**Comment by woodywall** [comment]
I saw that but didn't think to try the -windows7 version. That did the trick! Thanks for you help and for providing these great tools.

**Comment by baconpaul** [comment]
Glad it worked!
