### ISSUE TITLE
Optional DC offset removal/warning, and some categorization questions

### ISSUE THREAD

**Issue by fotisandstuff** [baconpaul/airwin2rack#176]
I have three questions:

1) First, as we know, there are some Airwindows plugins that can trap dangerous DC voltage energy, such as Deckwrecka, BassAmp, Creature (the latter of which even included in the Recommended section!), and even a plugin that literally does that, called DCVoltage. I am afraid that this may cause issues to people who are using DC-coupled systems. Would it be a good idea if the Consolidated plugin had an optional DC offset remover just before the final output stage? Or, even better, an optional clamp that kills anything below 20Hz and anything above 20 (similar to Infrasonic) or 22kHz (similar to Ultrasonic and Hypersonic). I've heard that the problem with Infrasonic is that it adds too much group delay, so maybe a very steep implementation of Hermepass could be useful. An optional safety clipper at the end (like ClipOnly2) wouldn't hurt, either.

2) Why is DubSub2 under the Bass category and Weight under the Filter category, since they are fairly similar?

3) I noticed that none of the Amp Sims is in the Recommended section. Does Chris not like those plugins at all?

**Comment by baconpaul** [comment]
On 2 and 3, it's all up to @airwindows 

On 1, I've told chris I'm not going to get in the signal path *at all* other than amplitude scaling for gain staging. Can you just add a DC blocker of choice downstream?

**Comment by baconpaul** [comment]
Thanks chris (and happy holidays both and merry christmas if that's your thing)

I'll close this issue as resolved for the categories and wont-do for the dc blocker.
