### ISSUE TITLE
Polyphonic to polyphonic output channels are mono

### ISSUE THREAD

**Issue by nnbveh** [baconpaul/airwin2rack#24]
Hi, i'm using the airwindows module as an insert with mixmaster, and the channels are returned as mono signals, not stereo, not sure if that is normal or a bug, i've tried other poli-modules in the place of yours and they all return stereo signals on every channel...

i'm on windows 11, latest vcv pro version.

Thanks!

**Comment by nnbveh** [comment]
actually yes, your module does it as well...only left channel has sound

**Comment by nnbveh** [comment]
<img width="573" alt="Screenshot 2023-08-15 233831" src="https://github.com/baconpaul/airwin2rack/assets/39271290/d672fbe3-b9d2-48fb-a6a9-2b115983f71f">

I supposed to hear  sine in left channel and Square in the right, but i hear only sine, in both...

if i get rid of airwindows module i can hear both properly

**Comment by baconpaul** [comment]
I’ll take a look sure. Maybe I index shuffled wrong! 

Thanks

**Comment by baconpaul** [comment]
Indeed I did! Thank you for the excellent bug report and sorry for the braindead bug. https://github.com/baconpaul/airwin2rack/commit/b51407c6f36d9461d8164a9c8bfa3c7de088b299 fixes this.

This will be in a nightly https://github.com/baconpaul/airwin2rack/releases/tag/Nightly shortly and I'll queue it up for the library this week.

**Comment by baconpaul** [comment]
OK I branched this into a 2.5.1 release also and submitted it to the [library](https://github.com/VCVRack/library/issues/751#issuecomment-1679779198)

**Comment by baconpaul** [comment]
This should now be in the library

**Comment by nnbveh** [comment]
Great! Works as expected! thank you.
