### ISSUE TITLE
Can't change effect type using the menu or selector arrows.

### ISSUE THREAD

**Issue by RobU23** [baconpaul/airwin2rack#25]
Hi, 

The Airwindows rack plugin is (practically) stuck on Galactic Reverb. It loads with GR as default, but the effect cannot be changed.  The other effects appear in the menu but selecting them does nothing, and neither does using the left/right selection buttons.

If I set Randomise to 'changes fx choice', it does indeed pick a random effect, but this is not great for reproduceability with 350 effects on offer :-)

I've tried uninstalling, restarting VCV, reinstalling, but get the same behaviour. 

VCV Rack 2.4.1 (standalone or VST) on Windows 10.

Cheers

**Comment by baconpaul** [comment]
Do you have an audio output running?

**Comment by RobU23** [comment]
Hey Paul, thanks for the incredibly rapid response :)

You are absolutely correct, if I hook Airwindows into an existing patch, or add an output to the patch I'm building, it works as expected - I feel like a bit of an idiot for not trying that, but many thanks for this, I am up and running :)

All the best
R

**Comment by baconpaul** [comment]
Great. I’ll see if there’s an easy fix for the non audio case for a future version

**Comment by RichCaloggero** [comment]
I'm using this is reaper (both the vst3 and clap versions) and get this behavior. Oddly, I can change the effect the first time, but after that, nothing I do will change the effect. Even if I remove the airWindows plugin altogether from the project, then re-add it, I cannot change it.

It seemed to work for a while when I had audio playing, but after about 20 minutes, that stopped as well. Now I cannot change it at all!

**Comment by baconpaul** [comment]
Yeah we had a bug where if audio wasn’t running the plugin type woudlnt change, we fixed it about 3 hours ago in the daw plugin, can you re download?
