### ISSUE TITLE
module not updated on vcv site

### ISSUE THREAD

**Issue by hornyjailfish** [baconpaul/airwin2rack#27]
Title.
Dont know why vcv library page dont have it updated for 2 months already

**Comment by baconpaul** [comment]
hi. 

there's been a month delay in getting modules out, but the integration platform is running again. I submitted 2.7.0 which you can download here 4 weeks ago and it should be in the library soon - i hope this week.

you can also always grab the nightly here which chris updates with every new effect. I generally push to the rack library every 8 weeks or so.

**Comment by hornyjailfish** [comment]
ok i'll switch to nightly builds then. Its pretty ez thanks to night-bin module from https://github.com/isivisi/questionablemodules

**Comment by baconpaul** [comment]
Oh neat I didn’t know about that

anyway like I said I submit to the library pretty regularly. But there’s been no library updates for a month from the rack team. They are back on track now though so should start updating again soon
