### ISSUE TITLE
 kCathedral2 reverb preset crashes Rack

### ISSUE THREAD

**Issue by fractalgee** [baconpaul/airwin2rack#28]
Airwin 2.9.0-nightly-d916c7d, MacOS 14.2.1, Rack 2.4.1 arm64

Selecting kCathedral2 reverb preset (nothing connected yet) crashes Rack with:

```
Thread 11 Crashed:: com.apple.audio.IOThread.client
0   plugin.dylib                  	       0x106998aa8 airwin2rack::kCathedral2::kCathedral2::processReplacing(float**, float**, int) + 4784
1   ???                           	        0xfffffff4 ???
2   plugin.dylib                  	       0x10668d9e8 AW2RModule::processMono(rack::engine::Module::ProcessArgs const&, bool) + 1032
3   libRack.dylib                 	       0x103525970 rack::engine::Module::doProcess(rack::engine::Module::ProcessArgs const&) + 168
4   libRack.dylib                 	       0x10351f0e4 rack::engine::Engine::stepBlock(int) + 1312
5   libRack.dylib                 	       0x10345b49c rack::audio::Device::processBuffer(float const*, int, float*, int, int) + 436
6   libRack.dylib                 	       0x10348db00 rack::RtAudioDevice::rtAudioCallback(void*, void*, unsigned int, double, unsigned int, void*) + 168
7   libRack.dylib                 	       0x103932ebc RtApiCore::callbackEvent(unsigned int, AudioBufferList const*, AudioBufferList const*) + 340
8   libRack.dylib                 	       0x103931fcc callbackHandler(unsigned int, AudioTimeStamp const*, AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*, void*) + 24
9   CoreAudio                     	       0x18749fefc HALC_ProxyIOContext::IOWorkLoop() + 9244
10  CoreAudio                     	       0x18749d3b0 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 108
11  CoreAudio                     	       0x18761c564 HALC_IOThread::Entry(void*) + 88
12  libsystem_pthread.dylib       	       0x184c7e034 _pthread_start + 136
13  libsystem_pthread.dylib       	       0x184c78e3c thread_start + 8
```

**Comment by baconpaul** [comment]
Hmmm just built and it works here. I'll have to look in more depth later with the actual nightly.

Wonder if it is another build booger? You had one of those a little while ago right? but seems very specific.

**Comment by fractalgee** [comment]
yep, had one of those a little while back in SurgeXT Rack. Anyhow, doesn't crash 100% of the time, but somewhat 2 out of 5 times or so. Not tried actually using it of it worked though, got busy on another patch that needed more help ;)

**Comment by baconpaul** [comment]
I chatted with @airwindows a bit about it. Theres a chance the code has a memory scribble somewhere perhaps also?

I don't *think* it is the rack wrapper but haven't investigated at length yet.

**Comment by fractalgee** [comment]
seeing that there is the ??? line just before the function call that
aborts, it seems indeed that something trashes the call pointer (stack)
somehow. I hope you can find it. But again, it's hit or miss whether it
crashes, however stack is always same when it does, so that seems at least
not a moving target.

**Comment by airwindows** [comment]
If we can figure out what the heck is happening, the entire class of code that works like this can be strengthened. I've seen crashes on my old laptop using the AU or VST version of this, particularly under memory pressure, but it's already out at the limits of my coding abilities and so far I can't see what would be causing it.

What I've seen on the old laptop is: load in TwistedWave and select 'apply and close' and crash, play the effect on audio without apply and close and it plays, apply without closing the effect window and it plays (occasionally even this can crash the program, though). Something is clearly up.

**Comment by fractalgee** [comment]
no memory pressure here, Rack is only thing running, and that takes way less than half the memory on this M1 Mini on a huge patch  (the 16GB version). I run out of CPU before ever getting to running out of memory. This is all standalone Rack, and for the most part Rack is rock solid. 
I hope these weird ones do help make the code more solid, hence me diligently logging them. Wish I could give you more to go on, but alas, I seem good at triggering weird crashes ;)

**Comment by chinenual** [comment]
Similar crash with the older kCathedral in case that helps triangulate.

MacOS Ventura 13.6.4
M2 MAX 64G 
Rack Pro 2.4.1 (x86 via Rosetta)
Airwindows 2.8.0

```
Thread 18 Crashed:: com.apple.audio.IOThread.client
0   <translation info unavailable>	       0x1006f3b20 ???
1   plugin.dylib                  	       0x113b08c10 airwin2rack::kCathedral::kCathedral::processReplacing(float**, float**, int) + 1360
2   libsystem_platform.dylib      	    0x7ff8119ac603 _sigtramp + 51
3   plugin.dylib                  	       0x11376cb15 AW2RModule::processMono(rack::engine::Module::ProcessArgs const&, bool) + 1237
4   libRack.dylib                 	       0x109a77dff rack::engine::Module::doProcess(rack::engine::Module::ProcessArgs const&) + 143
5   libRack.dylib                 	       0x109a709b3 rack::engine::Engine::stepBlock(int) + 1699
6   libRack.dylib                 	       0x109996c05 rack::audio::Device::processBuffer(float const*, int, float*, int, int) + 325
7   libRack.dylib                 	       0x1099cf37f rack::RtAudioDevice::rtAudioCallback(void*, void*, unsigned int, double, unsigned int, void*) + 143
8   libRack.dylib                 	       0x109ec393f RtApiCore::callbackEvent(unsigned int, AudioBufferList const*, AudioBufferList const*) + 335
9   libRack.dylib                 	       0x109ec2935 callbackHandler(unsigned int, AudioTimeStamp const*, AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*, void*) + 21
10  CoreAudio                     	    0x7ff813a7850c HALC_ProxyIOContext::IOWorkLoop() + 7734
11  CoreAudio                     	    0x7ff813a76041 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 80
12  CoreAudio                     	    0x7ff813be593e HALB_IOThread::Entry(void*) + 72
13  libsystem_pthread.dylib       	    0x7ff81197f1d3 _pthread_start + 125
14  libsystem_pthread.dylib       	    0x7ff81197abd3 thread_start + 15
```

**Comment by baconpaul** [comment]
Yeah it must be scribbling memory 

I’ll try and do a sanitizer build under CLion and see if I can see it

Chris you probably have an index typo one place and are writing out of bounds. But there’s lots of indices..,,

**Comment by airwindows** [comment]
Sure are. Thing is they're all indices to a pattern… and I thought I had a little buffer space in every last one of them, so it's puzzling. All those banks of indices are very regular in how they're implemented.

ClearCoat is a somewhat similar arrangement but without the buffers (predelay and an additional predelay for an extra bass delay). kCathedral and kCathedral2 have different sized early reflection matrices but the same pair of predelay topology, and it's a longish delay by the standards of most of the indices.

**Comment by chinenual** [comment]
In my case, kCathedral seems happy as long as no other Airwindows modules are present in the patch.   If I do this:

- Add Airwindows - select kCathedral - connect it and enjoy the reverb
- Add another Airwindows - leave it defaulted to Galactic - don't bother connecting any ports
- Add another Airwindows - select kCathedral and KABOOM - rack crashes.  

This is roughly what happened the first time I encountered the crash a few days ago.  I just reproduced it in a simple patch as a sanity check to see if it might be related to multiple instances stepping on each other.

**Comment by baconpaul** [comment]
Super useful

**Comment by fractalgee** [comment]
my crash was/is with a single Airwindows instance, just FYI.

**Comment by baconpaul** [comment]
Sigh. I just added 15 kCathedaral2 to my session and got no crash.

I think i just have to run under sanitizer. That takes a bit of time. Will look on weekend.

**Comment by airwindows** [comment]
FWIW I'm going after it in the original plugins, for instance by making an alternate kCathedral2 and trying to remove parts to find the bit that's crashing.

Unfortunately it's not going well. I have been doing things like removing all the early reflection 4x4 matrix, or feedback loop filtering, but it's not helping. My test case was this: instantiate the new version in my old version of TwistedWave with Xcode also running, 'apply and close' on full wet, undo, set wetness control to around 0.2 and 'play' and TwistedWave would reliably crash. Nothing that I did would stop the crash except (I think?) commenting out the whole plugin and trying to do just pass-through of the input samples.

Unfortunately, the next thing I did was instantiate the new version in my old version of TwistedWave with the same file as before, and mistakenly 'apply and close' with the 0.2 setting. And it worked, and then every subsequent attempt worked and it was done crashing for the day, no matter what else I enabled in the plugin.

I'll get back to trying to get a repeatable crash later today? If anyone hits on an answer I'd be excited to hear it. I've found some minor bugs but those sections don't seem to be crash-inducing, they're just applying filtering more lightly than I thought I was doing.

**Comment by baconpaul** [comment]
I built it under asan and no crash no out of bounds. 
i duplicated a kcath2 30 times in rack and no crash no out of bounds

i'm not sure what the problem is but i can't reproduce or see any over here.

**Comment by airwindows** [comment]
Yeah… I mean, I'm not that clever but I keep my stuff pretty straightforward for a reason. I didn't see where a problem would be coming from, and I've not had a lot of luck stripping out stuff to isolate the problem.

I'll keep at it, all the more because the framework is one I'm going to be building more reverbs on. I know I'm doing a whole lot of const int making, and array-making. kCathedral2 is just upping the ante by making even more (4x4 + 5x5 plus a few extras), all with the same basic formulation.

**Comment by baconpaul** [comment]
@airwindows dint know if you saw on discord but I think naren found this and has a patch for you to apply then re-button

**Comment by baconpaul** [comment]
OK this is fixed in the next nightly (building now) and I'll submit to the library this week so 2.10 should include it!

**Comment by baconpaul** [comment]
Yeah I can definitely overdrive it also. I don't know if that's a bug, that's just what kCathederal2 seems to do.

In the release you have there's an input attenuator slider below the inputs by the way. So you can cut there. But definitely when I send it a moderately hot signal it goes into crazy overdrive for me too. @airwindows  - intentional?

**Comment by fractalgee** [comment]
Given that the input is -6dB I would think it may be a bug, none of the other reverb types seem to overdrive that badly. Even if I patch a VCA in between VCO and the kCathedral2 inout I can still hear crackles at VCA being at 35% where the mixer channel now also shows a -2dB or so  signal. So also seems to overdrive internally.

**Comment by baconpaul** [comment]
yeah i agree

just I don' think it is a bug in exposing kCathederal to rack or juce; i think its just a bug in kCathederal, so need chris to chime in!
