### ISSUE TITLE
Galactic2 nan doesn't recover

### ISSUE THREAD

**Issue by baconpaul** [baconpaul/airwin2rack#29]
Another from @fractalgee to which I responded "I should add nancheck clears"

Take 2 airwin instances, set both to Reverb->Galactic2. Connect out1 to in 2 and out 2 to some destination (mixer/scope, doen’t matter. Now connect a SurgeXT FM2 VCO (guess any other wil do too) and observer a nanV on outs on either instance 1 or 2, seems to depend in which order they are wired. Switching to Galactic on the nanV one will make it work again (or any other reverb preset)

Was just seeing what a chain of Galactic2s would sound like, but alas, no dice

I

**Comment by fractalgee** [comment]
any chance to sort out this one, pretty please?

**Comment by baconpaul** [comment]
oh did i not add nancheck sweeps to the rack module? I'll do it in my next sweep. 

I still couldn't make galactic 2 nan out in my test case though. Do you have a patch which does it reliably?

**Comment by fractalgee** [comment]
Just grabbed the latest nightly (should have done that before previous comment, as I had failed to do so since the official drop) and lo and behold, no more nanV! So go ahead and close this one as sorted.

**Comment by baconpaul** [comment]
Great!
