### ISSUE TITLE
exclude gain bars from random

### ISSUE THREAD

**Issue by firolightfog** [baconpaul/airwin2rack#59]
Hi,

I typically use the random function to explore the real character of a certain effect. To keep this great practice I'd like the gain slidebars to be excluded from the random function. Could you please make it happen?

<img width="404" alt="image" src="https://github.com/baconpaul/airwin2rack/assets/34127628/5b666c53-169e-4cad-8409-28b512e4f56f">

Many thanks, Andras

**Comment by baconpaul** [comment]
Oh man yeah they should not be in random. Good call. Thank you.,

**Comment by baconpaul** [comment]
Just pulled the 2.10.0 release from the library. Phew. Will fix and submit a 2.11.0. Thanks again

**Comment by baconpaul** [comment]
OK just pushed a version which will fix that. New nightly in ~30 minutes. If you can give it a whirl and if that works, I'll close this and submit 2.11 to the library

Thank you very much!
