### ISSUE TITLE
Parameter controls

### ISSUE THREAD

**Issue by jimhuds** [baconpaul/airwin2rack#60]
First of all, thank you for making this!

A small feature request: double click or control click (or whatever the standard is) to reset the parameter value to default would be great! Also if we could type values in then that'd be even better.

Cheers

**Comment by baconpaul** [comment]
both those features are in the latest version! Which one are you running?

Double click a knob resets and click a value makes it a type for all non-discrete values

**Comment by baconpaul** [comment]
also glad you like it!

**Comment by baconpaul** [comment]
Awesome! “Official” launch happens Monday so appreciate the request even though I was a day ahead of you :)

a separate user asking the same question four days ago is why we have the feature 

anyway enjoy the plugin!
