### ISSUE TITLE
Airwindows Consolidated: Cycling plugins with buttons will skip a plugin every few plugins

### ISSUE THREAD

**Issue by mthierman** [baconpaul/airwin2rack#62]
Cycle up or down through the plugins, after 2-4 plugins it may skip a plugin. Seems to be worse if you go up and down in the list instead of one direction.

**Comment by baconpaul** [comment]
Oh I wonder if my long hold timer is wonky. I bet it is

**Comment by baconpaul** [comment]
Yeah https://github.com/baconpaul/airwin2rack/blob/67c2a5c6c794870044fd96387c2528faa60ef0fd/src-juce/AWConsolidatedEditor.cpp#L292 should be a click counter not a bool
