### ISSUE TITLE
Plugin settings should be hidden on Linux

### ISSUE THREAD

**Issue by elcalenx** [baconpaul/airwin2rack#72]
So I just tried out the new Airwindows Consolidated plugin. Looks pretty impressive, but one of the first things I noticed is that there is now an "AirwindowsConsolidated" directory inside my home directory.

This is something that always bugs me when I encounter it. I think it is generally best practise on Linux to save application settings in a hidden location, so as not to clutter the user's home directory. This could be done  by either naming the settings directory something like ".AirwindowsConsolidated", or (quite common practise these days and probably better) creating it inside a common settings directory like "~/.config/".

**Comment by baconpaul** [comment]
Oh I just use the juce default location for properties. I’ll add this to the list to figure out this year and will borrow some of the surge XDG code.

**Comment by baconpaul** [comment]
Notes to self 

https://github.com/baconpaul/airwin2rack/blob/303dcd81aa1867f5d6dedfc0f3ea2cd5060374b8/src-juce/AWConsolidatedEditor.cpp#L1136

uses get default file plus the dir

juces choice on linux isn’t great

https://docs.juce.com/master/structPropertiesFile_1_1Options.html#a2e20c2c3ce5012d69cc70d4e38763c39

so I think an if juce linux and change the folder to .blah or .config/blah and test is the way to fix this

**Comment by baconpaul** [comment]
I've decided to fix this today before we promulgate more incorrect usage.

**Comment by baconpaul** [comment]
I have merged the fix for this and tested it on Ubuntu where my properties file now lives in ~/.config/AirwindowsConsolidated

It will take about 20 minutes for a new binary to be created, signed, uploaded, etc...

Thank you for reporting this. We should have caught it in the beta period!

**Comment by elcalenx** [comment]
Nice!

I've complained about this on several open source projects over the years, including I think Surge back in the day. I guess it's become a bit of a pet peeve of mine. What can I say, I just like to see a clean home directory. :smile:

**Comment by baconpaul** [comment]
Yeah the fact that the JUCE api does the right thing on mac/win and the wrong thing on lin is a bit of a bummer. 

https://github.com/baconpaul/airwin2rack/commit/8f9eaad1b588e4dc11febb77426b4443af77b506

you can see what I had to do to make it work

But thanks for reporting it.
