### ISSUE TITLE
Feature request: Rename label for Ardour?

### ISSUE THREAD

**Issue by mahlonsmith** [baconpaul/airwin2rack#82]
I don't know if this is actually possible given plugin limitations, but I thought I'd ask anyway:  Having a stack of Airwindows, it's hard to find what is where in the DAW plugin without opening everything individually.   Is there any mechanism available for signalling up the chain to dynamically rename the plugin label?

![2024-05-06_20-05](https://github.com/baconpaul/airwin2rack/assets/3220479/1ea1d9c1-503a-4687-9017-9ebc4218d366)

... Love this collaboration, btw.  Fantastic idea.

**Comment by baconpaul** [comment]
This is a very frequent request in the first day. Unfortunately none of the plugin APIs provide a way to dynamically rename a plugin, so we can't change that display.

**Comment by mahlonsmith** [comment]
I suspected as much -- not unique to Airwindows Consolidated, similar issues with Cardinal FX, etc - I think I'll make an arbitrary "labelling" feature request on the Ardour side of things.   Thanks for the quick confirmation/response!

**Comment by mahlonsmith** [comment]
And of course, that has already been in Ardour since 7.4, I've just never had a reason to use it until recently.  "Rename" is available in the context menu, so this is totally moot.  Excellent.

**Comment by baconpaul** [comment]
Great!
