### ISSUE TITLE
Compiling for Linux ARM? 

### ISSUE THREAD

**Issue by Deftaudio** [baconpaul/airwin2rack#89]
Hi there, great work and thank you for sharing pre-compiled binaries. 
Would you, please, provide instructions to compile on Pi OS?

**Comment by baconpaul** [comment]
The instructions are the same on all platforms. Just follow the readme instructions and it will all work. The zynthian crew already got it built!

**Comment by baconpaul** [comment]
Specifically https://github.com/baconpaul/airwin2rack?tab=readme-ov-file#the-juce-plugin will work if your machine is set up to compile juce plugins. The GitHub workflow shows the packages we grab on Ubuntu if you get a missing dep
