### ISSUE TITLE
minor bug with generic daw gui when Consolidated plugin gui is turned off

### ISSUE THREAD

**Issue by mendeley13** [baconpaul/airwin2rack#94]
If Consolidated gui is turned off, generic daw gui of Consolidated plugin works wrong:
if daw is playing at the time when I am tweaking a parameter, the 3rd digit after the point switches to an adjacent value when I release my mouse button. If I am increasing the value, it jumps to an adjacent higher number. If I am decreasing – it jumps to an adjacent lower number. If daw is not playing, there is no such problem. 
This problem is specific to VST3 format, in CLAP there is no such problem. I am using Reaper 7 on Windows 10 x64.

I discovered one more little problem with generic daw gui. This one is specific for CLAP. VST3 doesn’t have this problem:
If at the time when I launch my daw, my audio interface hardware device is unplugged from my computer, then daw generic gui of Consolidated doesn’t work: sliders moving doesn’t affect the values of parameters. 
In order to make it work again, I have to connect my audio interface hardware device to computer and start playback of my daw for at least one second.

**Comment by mendeley13** [comment]
This functionality already exists. I discovered it too late, my bad.

**Comment by baconpaul** [comment]
Thanks 

mind sharing your os? 

This won’t make a “this week” cut to fix but I’ll poke at it soon indeed

**Comment by baconpaul** [comment]
Oh you said windows sorry!

**Comment by mendeley13** [comment]
I discovered one more little problem with generic daw gui. This one is specific for CLAP. I edited my first comment to describe it there.

**Comment by baconpaul** [comment]
thank you

there have been a *lot* of fixes this week to deal with running without audio threads and different problems (this is tricky for a technical reason involving the way vst2 vs 3/clap/au render strings). I'll definitely look at this in my next sweep of the plugin but if you could share the version or build date you are running that would be great, and if it is older than yesterday, perhaps give another try with the latest?

Appreciate the help. The community bug hunting this week has been outstanding!

**Comment by mendeley13** [comment]
I updated to the newest version:
AirwindowsConsolidated-2024-05-09-872b7c8-Windows-64bit-setup
bugs I am describing are still present in it.
I am glad my feedback helps. I was afraid I am being annoying.

**Comment by baconpaul** [comment]
Well I can at least confirm that I see the VST3 bug in reaper. Wonder what it is!!

**Comment by baconpaul** [comment]
Ahh I found it. Ha. What an excellent bug report.

**Comment by baconpaul** [comment]
Alright I am quite sure these are the same thing but I couldn't replicate the CLAP one just the VST3

It takes about 30 minutes to make a build; If you can pull the build when it updates and test again I would appreciate it. If you still see the problem please reopen this issue.

Best

**Comment by mendeley13** [comment]
I tested the new updated version. Both bugs that I have described are fixed now.

**Comment by baconpaul** [comment]
Wonderful! Thank you for the super detailed report. It helped me catch a more fundamental bug.

Enjoy the plugin!
