### ISSUE TITLE
UnBox.txt vs Unbox.txt on Mac

### ISSUE THREAD

**Issue by hollance** [baconpaul/airwin2rack#96]
This is only a tiny issue but I just cloned the repo on my Mac and git gives the following warning message:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'res/awpdoc/UnBox.txt'
  'res/awpdoc/Unbox.txt'
```

I checked and these files seem to be identical, so perhaps it's a good idea to remove one of them (presumably Unbox.txt since the actual plug-in is named UnBox).

**Comment by baconpaul** [comment]
Thanks yeah an ancient version of the pedia must have had a case typo. I deleted the `Unbox` one just now

Thank you!
